"""
install.py — Registry installer for map_structure context menu.

Auto-detects script location and registers Windows context menu entries.
Run once after moving the script to its final location.

Usage:
    python install.py              # install context menu
    python install.py --uninstall  # remove context menu
"""

import os
import sys
import argparse
import subprocess


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LAUNCHER_BAT = os.path.join(SCRIPT_DIR, "map_structure_launcher.bat")


# Registry template with {launcher_path} placeholder
REGISTRY_TEMPLATE = """Windows Registry Editor Version 5.00

; Adds "Map Structure" to right-click context menu for folders
; Auto-generated by install.py

[HKEY_CURRENT_USER\\Software\\Classes\\Directory\\shell\\MapStructure]
@="Map Structure"
"Icon"="python.exe,0"

[HKEY_CURRENT_USER\\Software\\Classes\\Directory\\shell\\MapStructure\\command]
@="cmd /c \\"\\\"{launcher_path}\\\\" \\"%1\\"\\"\\""

; Also add to background right-click (inside an open folder)
[HKEY_CURRENT_USER\\Software\\Classes\\Directory\\Background\\shell\\MapStructure]
@="Map Structure"
"Icon"="python.exe,0"

[HKEY_CURRENT_USER\\Software\\Classes\\Directory\\Background\\shell\\MapStructure\\command]
@="cmd /c \\"\\\"{launcher_path}\\\\" \\"%V\\"\\"\\""
"""

UNINSTALL_TEMPLATE = """Windows Registry Editor Version 5.00

; Remove "Map Structure" context menu entries

[-HKEY_CURRENT_USER\\Software\\Classes\\Directory\\shell\\MapStructure]
[-HKEY_CURRENT_USER\\Software\\Classes\\Directory\\Background\\shell\\MapStructure]
"""


def create_registry_file(install: bool = True) -> str:
    """
    Create .reg file with actual script paths.

    Args:
        install: If True, create install file; if False, create uninstall file

    Returns:
        Path to created .reg file
    """
    if install:
        # Escape backslashes for registry format
        launcher_escaped = LAUNCHER_BAT.replace("\\", "\\\\")
        content = REGISTRY_TEMPLATE.format(launcher_path=launcher_escaped)
        filename = "map_structure_install.reg"
    else:
        content = UNINSTALL_TEMPLATE
        filename = "map_structure_uninstall.reg"

    reg_path = os.path.join(SCRIPT_DIR, filename)

    with open(reg_path, "w", encoding="utf-8") as f:
        f.write(content)

    return reg_path


def apply_registry_file(reg_path: str) -> bool:
    """
    Apply .reg file to Windows registry.

    Args:
        reg_path: Path to .reg file

    Returns:
        True if successful, False otherwise
    """
    try:
        # Use regedit to import the registry file
        result = subprocess.run(
            ["regedit.exe", "/s", reg_path],
            check=True,
            capture_output=True,
        )
        return result.returncode == 0
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def verify_launcher_exists() -> bool:
    """
    Check if launcher batch file exists.

    Returns:
        True if launcher exists, False otherwise
    """
    return os.path.isfile(LAUNCHER_BAT)


def main():
    """Main installer entry point."""
    parser = argparse.ArgumentParser(
        description="Install or uninstall map_structure context menu.",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove context menu entries",
    )
    args = parser.parse_args()

    print("=" * 70)
    print("Map Structure - Context Menu Installer")
    print("=" * 70)
    print()

    # Verify launcher exists (not needed for uninstall)
    if not args.uninstall and not verify_launcher_exists():
        print(f"ERROR: Launcher not found at:")
        print(f"  {LAUNCHER_BAT}")
        print()
        print("Make sure map_structure_launcher.bat exists in the same directory.")
        sys.exit(1)

    # Show detected paths
    if not args.uninstall:
        print("Detected paths:")
        print(f"  Script directory: {SCRIPT_DIR}")
        print(f"  Launcher:         {LAUNCHER_BAT}")
        print()

    # Create registry file
    action = "uninstall" if args.uninstall else "install"
    print(f"Creating {action} registry file...")
    reg_path = create_registry_file(install=not args.uninstall)
    print(f"  Created: {reg_path}")
    print()

    # Apply registry changes
    print(f"Applying registry changes...")
    success = apply_registry_file(reg_path)

    if success:
        print("✓ Registry updated successfully!")
        print()
        if args.uninstall:
            print("Context menu entries removed.")
        else:
            print("Context menu installed. Right-click any folder to see 'Map Structure'.")
    else:
        print("✗ Failed to apply registry changes.")
        print()
        print("You can manually double-click the .reg file to install:")
        print(f"  {reg_path}")

    print()
    print("=" * 70)


if __name__ == "__main__":
    main()
